apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{include "common.labels" "frontend" | nindent 4}}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{include "common.labels" "frontend" | nindent 6}}
  template:
    metadata:
      labels:
        {{include "common.labels" "frontend" | nindent 8}}
    spec:
      containers:
      {{include "chaosmania.container" . | nindent 6}}
      volumes:
      {{include "common.volumes" . | nindent 6}}
---
{{ include "chaosmania.service" "frontend" }}
---
{{ if .Values.hpa.enabled }}
{{ include "chaosmania.hpa" "frontend" }}
{{ end }}
